models/__init__.py
#!/usr/bin/python3
# coding: utf-8
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

models/user.py
#!/usr/bin/python3
# coding: utf-8
from sqlalchemy import Column, ForeignKey, ForeignKeyConstraint
from sqlalchemy import Integer, String

from models import db

# 模型之间的关系不需要创建第三个模型类来实现第三张关系表创建
# 创建用户和 角色的关系表
user_role = db.Table('user_role',
                     Column('user_id', Integer, ForeignKey('user.id', name='user_role_fk')),
                     Column('role_id', Integer, ForeignKey('role.id', name='user_role_pk')))


class BaseModel(db.Model):
    __abstract__ = True  # 作用： 不会创建模型的对应的表
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(20), unique=True, nullable=False)


class Role(BaseModel):
    __tablename__ = 'role'


class QX(BaseModel):
    __tablename__ = 'qx'


class User(db.Model):
    id = Column(Integer,
                primary_key=True,
                autoincrement=True)
    phone = Column(String(20),
                   unique=True,
                   nullable=False)
    auth_key = Column(String(100), nullable=False)
    nick_name = Column(String(20))
    photo = Column(String(100))

    # role_id = Column(ForeignKey('role.id'))
    # Many-to-Many 多对多的关系，指定secondary设置关联的表，Table()
    roles = db.relationship(Role, secondary=user_role)

mainapp/__init__.py
#!/usr/bin/python3
from logging import FileHandler

from flask import Flask
import settings
import logging
from flask.logging import default_handler


app = Flask(__name__, )
app.config.from_object(settings.Dev)

app.logger.removeHandler(default_handler)
app.logger.setLevel(logging.INFO)

fmt = logging.Formatter(fmt='%(asctime)s %(name)s %(levelname)s: %(message)s',
                        datefmt='%Y-%m-%d %H:%M:%S')

file_handler = FileHandler('edu.log')
file_handler.setLevel(logging.INFO)
file_handler.setFormatter(fmt)

app.logger.addHandler(file_handler)

mainapp/views/__init__.py
#!/usr/bin/python3
# coding: utf-8

mainapp/views/logger_v.py
#!/usr/bin/python3
# coding: utf-8
from flask import Blueprint, request, jsonify


blue = Blueprint('loggerBlue', __name__)


@blue.route('/log', methods=['POST'])
def upload_log():
    print(request.form)
    return jsonify({
        'msg': 'ok'
    })

mainapp/views/user_v.py
#!/usr/bin/python3
# coding: utf-8
import uuid
from datetime import datetime, timedelta

import os
from flask import Blueprint, make_response, redirect, jsonify
from flask import request, render_template
from werkzeug.datastructures import FileStorage

import settings
from models.user import User, db
from utils import crypt, cache

blue = Blueprint('userBlue', __name__)


@blue.route('/modify', methods=['GET', 'POST'])
def modify():
    # print('request-method: ', request.method)

    token = request.cookies.get('token')
    user_id = cache.get_user_id(token)

    # 任务2： 优化登录用户的相关信息存在redis中(缓存)
    user = User.query.get(int(user_id))

    msg = ''
    if request.method == 'POST':
        # 头像上传
        # 获取上传的文件
        # user_photo必须和前端请求中文件字段名保持一致
        upload_file: FileStorage = request.files.get('user_photo')
        print('文件名： ', upload_file.filename)
        # print('文件长度（字节）： ', upload_file.content_length)
        print('文件类型： ', upload_file.content_type)
        # 验证文件是否为图片
        if not upload_file.content_type.startswith('image/'):
            msg = '只支持图片上传'
        else:
            # 保存图片
            filename = uuid.uuid4().hex + os.path.splitext(upload_file.filename)[-1]
            filepath = os.path.join(settings.USER_DIR, filename)

            # 服务端保存上传的文件
            upload_file.save(filepath)

            # 更新用户信息
            # 保存在数据库的图片是相对static资源访问的路径
            user.photo = 'user/' + filename
            db.session.commit()

    return render_template('user/info.html',
                           user=user,
                           msg=msg)


@blue.route('/upload', methods=['POST'])
def upload_photo():
    upload_file: FileStorage = request.files.get('photo')

    filename = uuid.uuid4().hex + os.path.splitext(upload_file.filename)[-1]
    filepath = os.path.join(settings.USER_DIR, filename)

    upload_file.save(filepath)

    user = User.query.get(cache.get_user_id(request.cookies.get('token')))
    # 任务1： 删除之前的用户头像

    user.photo = 'user/' + filename;
    db.session.commit()

    # ? 图片如何压缩- PIL(pip install pillow)

    return jsonify({
        'msg': '上传成功',
        'path': 'user/' + filename
    })


@blue.route('/logout', methods=['GET'])
def logout():
    # 删除redis中token
    token = request.cookies.get('token')
    cache.clear_token(token)

    # 删除cookie
    resp = redirect('/user/login')
    resp.delete_cookie('token')

    return resp


@blue.route('/login', methods=['GET', 'POST'])
def login():
    message = ''
    if request.method == 'POST':
        phone = request.form.get('phone')
        passwd = request.form.get('passwd')

        login_user = User.query.filter(User.phone == phone,
                                       User.auth_key == crypt.pwd(passwd)).one()
        if login_user:
            # 登录成功
            # 生成token
            token = uuid.uuid4().hex
            resp = redirect('/')
            resp.set_cookie('token', token, expires=(datetime.now() + timedelta(days=3)))

            # 将token添加到redis, token-user_id
            cache.save_token(token, login_user.id)
            return resp
        else:
            message = '查无此用户'

    return render_template('user/login.html', msg=message)

utils/__init__.py
#!/usr/bin/python3
# coding: utf-8

from redis import Redis

rd = Redis(host='10.36.174.19',
           db=9,
           decode_responses=True)

mainapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Title</title>
    <style>
        .circle-img {
            border: none;
            width: 100px;
            height: 100px;
            border-radius: 50%;
            box-shadow: 5px 5px 5px lightgray;
        }
    </style>
</head>
<body>
 <h1>主页</h1>
 <p>
     <img class="circle-img"
          id="photoImg"
          title="点击图片更改"
          onclick="selectImg()"
          src="/static/{% if user.photo %}{{ user.photo }}{% else %}images/default_img.png{% endif %}" />
 </p>
 <input type="file"
        id="selectFile"
        style="display: none"
        onchange="upload(this.files[0])">

 <h3><a href="{{  url_for('userBlue.modify') }}">修改个人信息</a></h3>
<script>
    function $(domID) {
        return document.getElementById(domID)
    }
    function selectImg() {
        if(confirm('是否确定更改头像')){
            $('selectFile').click()
        }
    }

    function upload(file) {
        {# alert(file.name); #}
        {# console.log(file) #}

        if(file.type.startsWith('image/')){
            if(file.size <= 1024*1024*8){
                // 任务2： 使用fetch()函数实现文件上传
                let url ="{{ url_for('userBlue.upload_photo') }}";
                let request = new XMLHttpRequest();
                request.open('post',url, true);
                request.onload = function (ev) {
                    if(request.status==200 && request.readyState==4){
                        respText = request.responseText;
                        respJson = JSON.parse(respText)

                        console.log(respText, respJson)
                        $('photoImg').src='/static/'+respJson.path;
                    }
                };

                let formdata = new FormData();
                formdata.append('photo', file)

                // 发送请求
                request.send(formdata)

            }else{
               alert('上传的图片大小在2M以内')
            }
        }else{
           alert('只限图片上传')
        }
    }
</script>
</body>
</html>

mainapp/templates/user/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{{ user.nick_name }}的个人中心</title>
</head>
<body>
<h3>修改{{ user.phone }}用户的头像</h3>
<p>
    <img src="/static/{% if user.photo %}{{ user.photo }}{% else %}images/default_img.png{% endif %}"
         width="100"
         height="100">
</p>
<!-- 如果form表单请求的路径是当前url路径,可以省略 action -->
<form method="post" enctype="multipart/form-data">
    <input name="user_photo" type="file">
    <button>开始上传头像</button>
</form>
<p style="color:red;">
    {{ msg }}
</p>
</body>
</html>

mainapp/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Login</title>
</head>
<body>
  <h1> 用户登录页面</h1>
  <form name="login_form" action="/user/login" method="post">
      <input name="phone" placeholder="手机号"><br>
      <input type="password" name="passwd" placeholder="口令"><br>
      <button>登录</button> <a href="#">没有账号则先去注册</a>
  </form>
  <div id="val_info" style="color:red">
      {{ msg }}
  </div>
 <script>
     function $(id) {
         return document.getElementById(id);
     }

     // 设置表单提交函数

     document.forms[0].onsubmit =function(ev){
         if(! /\d{11}/.test(this.phone.value)){
             $('val_info').innerHTML = '手机号必须是11位';
             return false
         }

          if(! /\w{6,}/.test(this.passwd.value)){
             console.log(this.passwd.value);
             $('val_info').innerHTML = '口令是包含数字和字母的至少6位的字符串';
             return false
         }

          $('val_info').innerHTML = ''
     }
 </script>
</body>
</html>